export const BUILTIN_NOLO_AGENT_KEY = "agent-pub-01NOLOAPPBLD000000019KCKT0";
export const BUILTIN_APP_BUILDER_AGENT_KEY =
  "agent-pub-01APPBUILDER00000001YAII3I";
export const BUILTIN_ECOMMERCE_AGENT_KEY =
  "agent-pub-01ECOMMERCEAG00000001PYQ2J";
export const BUILTIN_AGENT_CREATOR_AGENT_KEY =
  "agent-pub-01NOLOAGENTCRT000000000001";
export const BUILTIN_FEEDBACK_AGENT_KEY =
  "agent-pub-01NOLOFEEDBACKA000000000R2";
export const BUILTIN_CHROME_OPERATOR_AGENT_KEY =
  "agent-pub-01CHROMEOPR000000000001";

export const BUILTIN_NOLO_AGENT_ID = "01NOLOAPPBLD000000019KCKT0";
export const BUILTIN_APP_BUILDER_AGENT_ID = "01APPBUILDER00000001YAII3I";
export const BUILTIN_ECOMMERCE_AGENT_ID = "01ECOMMERCEAG00000001PYQ2J";
export const BUILTIN_AGENT_CREATOR_AGENT_ID = "01NOLOAGENTCRT000000000001";
export const BUILTIN_FEEDBACK_AGENT_ID = "01NOLOFEEDBACKA000000000R2";
export const BUILTIN_CHROME_OPERATOR_AGENT_ID = "01CHROMEOPR000000000001";

export const BUILTIN_PLATFORM_AGENT_KEYS = [
  BUILTIN_NOLO_AGENT_KEY,
  BUILTIN_APP_BUILDER_AGENT_KEY,
  BUILTIN_ECOMMERCE_AGENT_KEY,
  BUILTIN_AGENT_CREATOR_AGENT_KEY,
  BUILTIN_FEEDBACK_AGENT_KEY,
  BUILTIN_CHROME_OPERATOR_AGENT_KEY,
] as const;

const BUILTIN_PLATFORM_AGENT_KEY_SET = new Set<string>(BUILTIN_PLATFORM_AGENT_KEYS);

export const isBuiltinPlatformAgentRecord = (agent: {
  dbKey?: string | null;
  id?: string | null;
}): boolean => {
  const dbKey = typeof agent?.dbKey === "string" ? agent.dbKey : "";
  if (dbKey && BUILTIN_PLATFORM_AGENT_KEY_SET.has(dbKey)) return true;

  const id = typeof agent?.id === "string" ? agent.id : "";
  if (!id) return false;

  return BUILTIN_PLATFORM_AGENT_KEYS.some((key) => key.endsWith(id));
};
